
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-admin}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  app:
    build: .
    volumes:
      - ./:/app
      - /app/vendor
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER_NAME: localhost
      APP_ENV: dev
      APP_SECRET: ChangeMe
      DATABASE_URL: postgresql://admin:password@database:5432/app
      REDIS_URL: redis://redis:6379
    depends_on:
      - database
      - redis

  redis:
    image: redis:7-alpine

  database_test:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app_test
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - "5433:5432"

volumes:
  caddy_data:
  caddy_config:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
