lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    set_cookies:
        BEARER:
            lifetime: null
            samesite: lax
            path: /
            domain: null
            secure: true
            httpOnly: true

    token_extractors:
        cookie:
            enabled: true
            name: BEARER

when@dev:
    lexik_jwt_authentication:
        set_cookies:
            BEARER:
                secure: false